import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const contractsOut = join(__dirname, "..", "contracts", "out");
const abiOut = join(__dirname, "..", "src", "shared", "abi.ts");

function extractAbi(contractName: string, fileName: string): string {
  const artifact = JSON.parse(
    readFileSync(join(contractsOut, fileName, `${contractName}.json`), "utf8")
  );
  return JSON.stringify(artifact.abi, null, 2);
}

const escrowVaultAbi = extractAbi("EscrowVault", "EscrowVault.sol");
const autoReleaseKeeperAbi = extractAbi(
  "AutoReleaseKeeper",
  "AutoReleaseKeeper.sol"
);

let sessionEscrowAbi = "[]";
try {
  sessionEscrowAbi = extractAbi("SessionEscrow", "SessionEscrow.sol");
} catch {
  console.warn("SessionEscrow artifact not found, skipping...");
}

const output = `// Auto-generated by scripts/sync-abi.ts — do not edit manually
// Run: npm run sync-abi

export const escrowVaultAbi = ${escrowVaultAbi} as const;

export const autoReleaseKeeperAbi = ${autoReleaseKeeperAbi} as const;

export const sessionEscrowAbi = ${sessionEscrowAbi} as const;
`;

writeFileSync(abiOut, output);
console.log(`ABI written to ${abiOut}`);
